name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-jvm-js:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
          
      - name: Run JVM and JS tests
        run: ./gradlew jvmTest jsTest
        
      - name: Generate coverage report
        run: ./gradlew koverXmlReport
        
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./build/reports/kover/report.xml

  test-macos:
    runs-on: macos-14
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Cache Kotlin Native tooling
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
          
      - name: Build macOS libraries
        run: ./gradlew macosX64MainKlibrary macosArm64MainKlibrary
        
      - name: Run macOS tests (native execution)
        run: ./gradlew macosX64Test macosArm64Test