name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Run tests (coverage disabled for simplified build)
        run: ./gradlew jvmTest jsTest
        
      - name: Update coverage badge (disabled - no kover in simplified build)
        if: false # disabled until kover is re-added
        run: echo "Coverage disabled for simplified build"