name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Run tests and generate coverage
        run: ./gradlew allTests koverXmlReport
        
      - name: Get coverage percentage
        id: coverage
        run: echo "percentage=$(./gradlew -q printCoverage)" >> $GITHUB_OUTPUT
        
      - name: Update coverage badge
        if: github.ref == 'refs/heads/master'
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ secrets.GIST_ID }}
          filename: klog-coverage.json
          label: Coverage
          message: ${{ steps.coverage.outputs.percentage }}%
          color: ${{ steps.coverage.outputs.percentage >= 80 && 'brightgreen' || steps.coverage.outputs.percentage >= 70 && 'yellow' || 'red' }}